services:
  api:
    build: ./webapi/
    container_name: mestreruan.api
    restart: always
    env_file:
      - .env
    ports:
      - "$WEBAPI_PORT:$WEBAPI_PORT"
    expose:
      - "$WEBAPI_PORT"
    networks:
      - mestreruan
    depends_on:
      - dba
  app:
    build: ./webapp/
    container_name: mestreruan.app
    restart: always
    env_file:
      - .env
    ports:
      - "$WEBAPP_PORT:$WEBAPP_PORT"
    expose:
      - "$WEBAPP_PORT"
    networks:
      - mestreruan
    depends_on:
      - dba
  dba:
    image: postgres:latest
    container_name: mestreruan.dba
    restart: always
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    expose:
      - "$POSTGRES_PORT"
    volumes:
      - ./App_Data/DB/:/var/lib/postgresql/data/
    networks:
      - mestreruan
  pga:
    image: dpage/pgadmin4:latest
    container_name: mestreruan.pga
    restart: always
    env_file:
      - .env
    ports:
      - "$PGADMIN_LISTEN_PORT:$PGADMIN_LISTEN_PORT"
    expose:
      - "$PGADMIN_LISTEN_PORT"
    depends_on:
      - dba
    networks:
      - mestreruan
networks:
  mestreruan:
