services:
  app:
    build: .
    container_name: mestreruan.api
    expose:
      - 8080:8080
      - 4433:4433
    networks:
      - mestreruan
    # depends_on:
    #   - db
    
networks:
  mestreruan: