services:
  api:
    build: ./webapi/
    container_name: mestreruan.api
    restart: always
    env_file:
      - .env
    ports:
      - "$WEBAPI_PORT:$WEBAPI_PORT"
    # - 4433:4433
    expose:
      - "$WEBAPI_PORT"
    networks:
      - mestreruan
    depends_on:
      - dba
  app:
    build: ./webapp/
    container_name: mestreruan.app
    restart: always
    env_file:
      - .env
    ports:
      - "$WEBAPP_PORT:$WEBAPP_PORT"
      #- 4443:4443
    expose:
      - "$WEBAPP_PORT"
    networks:
      - mestreruan
    depends_on:
      - dba
  dba:
    image: postgres:latest
    container_name: mestreruan.dba
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./App_Data/DB/:/var/lib/postgresql/data/
    networks:
      - mestreruan
  pga:
    image: dpage/pgadmin4:latest
    container_name: mestreruan.pga
    restart: always
    env_file:
      - .env
    ports:
      - 8088:8088
    expose:
      - 8088
    depends_on:
      - dba
    networks:
      - mestreruan
networks:
  mestreruan:
