services:
  api:
    build: ./webapi/
    container_name: mestreruan.api
    restart: always
    ports:
      - 8080:8080
      - 4433:4433
    expose:
      - 8080
    networks:
      - mestreruan
    depends_on:
      - dba
  app:
    build: ./webapp/
    container_name: mestreruan.app
    restart: always
    ports:
      - 80:80
      #- 4443:4443
    expose:
      - 80
    networks:
      - mestreruan
    depends_on:
      - dba
  dba:
    image: postgres:latest
    container_name: mestreruan.dba
    restart: always
    environment:
      POSTGRES_USER: "usuario"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "aplicacao"
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./App_Data/DB/:/var/lib/postgresql/data/
    networks:
      - mestreruan
  pga:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "mestre@ruan.com"
      PGADMIN_DEFAULT_PASSWORD: "123456789"
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
      PGADMIN_LISTEN_PORT: "8088"
    ports:
      - 8088:8088
    expose:
      - 8088
    depends_on:
      - dba
    networks:
      - mestreruan
networks:
  mestreruan:
